require 'colorize'
require 'pry'

# Create a 2-player guessing game where players take turns to answer simple addition problems.
# The math questions are automatically generated by the game.
# It should do this by picking two numbers between 1 and 20.
# Example prompt: "Player 1: What does 5 plus 3 equal?"

#--------------- Requirements ---------------------#

# 1. Both players start with 3 lives
# 2. They lose a life if they mis-answer a question
# 3. If a player gets a question wrong, the game should output the new scores for both players.
# 4. The game doesn't end until one of the players loses all their lives
# 5. When the game is over. Announce who won and what the other players score is.

@player_one = { lives: 3 }
@player_two = { lives: 3 }

@current_player = @player_one

def generate_question

  # Generate 2 random numbers to add
  first_num = rand(1...20)
  second_num = rand(1...20)
  @answer = first_num + second_num

  q = @current_player.object_id == @player_one.object_id ? "Player 1: " : "Player 2: " # @current_player will never be equal to == @player_one OR @player_two
  q += "What does #{first_num} plus #{second_num} equal?"

end

def log_player_scores
  puts "----- Score board -----".blue
  puts "Player 1: #{@player_one[:lives]}"
  puts "Player 2: #{@player_two[:lives]}"
end

def verify_answer
  unless gets.chomp.to_i == @answer
    @current_player[:lives] -= 1
    log_player_scores
  end
end

def switch_players
  @current_player = @current_player.object_id == @player_one.object_id ? @player_two : @player_one
end

def stop
  log_winner
end

def log_winner
  if @player_one[:lives] == 0
    puts "Player 2 wins!"
    puts @player_one[:lives]
  elsif @player_two[:lives] == 0
    puts "Player 1 wins!"
    puts @player_two[:lives]
  end
end

def play
  #--------------- Gameplay ---------------------#
  puts
  puts "----- Welcome to Two Player Math -----".blue
  while true
    if @player_one[:lives] > 0 && @player_two[:lives] > 0
      puts
      puts generate_question
      verify_answer
      switch_players
    else
      puts
      puts "----- Game over -----".blue
      stop
      break
    end
  end
end

play
